### ISSUE TITLE
Specific tag (or symbol) returns nothing

### ISSUE THREAD

**Issue by GlazeNine** [NO-ob/LoliSnatcher_Droid#172]
![Screenshot_20221208-034933](https://user-images.githubusercontent.com/120068759/206329505-b73eae18-f93d-45b4-a3c0-beb44cc1f0d0.png)
App version: 2.3.0 (178) / Play
Tag is "panty_&_stocking_with_garterbelt"
Affected boorus: gelbooru, rule34.xxx, xbooru, sankaku.
Rule34hentai and rule34paheal show pics but the tag there is "panty_AND_stocking_with_garterbelt" so maybe the "&" symbol is the problem here.

**Comment by dizzydoo** [comment]
Symbol is definitely the problem.
Tested gelbooru, danbooru and rule34.xxx via a browser with the same API requests that lolisnatcher sends and they returned nothing because they skipped encoding the `&` symbol in the tags. Changing it to the proper HTML encoding `%26` fixes it, but doesn't work in lolisnatcher since it looks like the `%` gets changed only, sending `%2526` instead

**Comment by NO-ob** [comment]
Yeah theres some weirdness with encoding special characters, theres a similar problem with +. I am unsure how this can be fixed currently.

**Comment by coolst3r** [comment]
t seems that the issue with LolSnatcher is that it is incorrectly encoding the "&" symbol in the API requests for certain websites. This results in the requests returning no results. The correct encoding for "&" in URL parameters is "%26", but it appears that LolSnatcher is converting it to "%2526", which is causing the problem.

**Comment by NANI-SORE** [comment]
Fixed in 2.3.3
