### ISSUE TITLE
All favorite gone

### ISSUE THREAD

**Issue by Hamburgers015** [NO-ob/LoliSnatcher_Droid#73]
I don't know how, but all my favorite are completely gone, the same as my tags.
I enabled remembering favorites and tags.
What should I do?

**Comment by NANI-SORE** [comment]
Android version? If it's 10 or below, check LoliSnatcher/config folder.
If there is no folder or store.db file is not present in there, maybe it was deleted by something.
In that case, nothing can be done, sadly.

**Comment by Hamburgers015** [comment]
I have android 11, is there another alternative?

**Comment by NANI-SORE** [comment]
If you don't have root, no. And there is probably a new db file created already.
Did settings/booru configs reset too when that happened?

**Comment by Hamburgers015** [comment]
The settings didn't change at all.
I reopened the app, and boom every favorite or saved tag was gone.

**Comment by Hamburgers015** [comment]
Weirdly, yes.

**Comment by NANI-SORE** [comment]
Then the old db was really overwritten by a new one.
I'm not sure how the old one could be deleted though, because it can happen only if:
- you cleared app data completely through system settings (this would clear boorus and app settings too)
- you deleted the db yourself through app settings
Even if the file got corrupted for some reason, it shouldn't create a new one.

**Comment by Hamburgers015** [comment]
That are only the db files I have on my phone.

**Comment by NANI-SORE** [comment]
You can't find our db file through search, it's inside the folder which you can't view without root

**Comment by Hamburgers015** [comment]
Oh, sorry

**Comment by NANI-SORE** [comment]
But we do have settings and db backup/restore functionality in development for 2.0 release

**Comment by Hamburgers015** [comment]
It's ok.
Thanks for help.
